server:
  port: 8080
spring:
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    template-loader-path: classpath:/webapp
    enabled: true
  redis:
    port: 6379
    host: 127.0.0.1